config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from tastypie.api import Api
from tastypie.utils import trailing_slash
from assets_manager.views import home
from assets_manager.api.resources import (
    AssetResource,
    AssetBucketResource,
)


# api
v1_api = Api(api_name='v1')
v1_api.register(AssetResource())
v1_api.register(AssetBucketResource())


urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('opac_ssm.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^search/', include('haystack.urls')),

    # Assets Manager
    url(r'^assets/', include('assets_manager.urls')),

    # API
    url(r'^api/', include(v1_api.urls)),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

opac_ssm/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

opac_ssm/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    name = models.CharField(_('Name'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

opac_ssm/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from opac_ssm.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse(
            'users:detail',
            kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse(
            'users:detail',
            kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

opac_ssm/templates/users/base.html
{% extends "base.html" %}
{% block title %}{% block head_title %}{% endblock head_title %}{% endblock title %}
{% block page_header_title %}{% endblock page_header_title %}
{% block sub_header %}{% endblock sub_header %}

{% block middle_section %}
  <div class="col-sm-12 col-md-12 main">
    {% include "includes/messages.html" %}
    {% include "includes/middle_section_headers.html" %}
    <div class="row well" style="margin-top: 40px">
        {% block inner %}{% endblock inner%}
    </div>
  </div>
{% endblock middle_section %}

opac_ssm/templates/users/user_detail.html
{% extends "users/base.html" %}
{% load static i18n %}

{% block title %}{% trans "User" %}: {{ object.username }}{% endblock %}
{% block page_header_title %}
  {% trans "User" %}: <strong>{{ object.username }}</strong>
{% endblock page_header_title %}

{% block inner %}
  <div class="col-md-6 col-md-offset-3">
    <table class="table table-striped">
      <tbody>
        <tr>
          <td>{% trans "Username" %}:</td>
          <td>{{ object.username }}</td>
        </tr>
        {% if object.name %}
          <tr>
            <td>{% trans "Name" %}:</td>
            <td>{{ object.name }}</td>
          </tr>
        {% endif %}
        <tr>
          <td>{% trans "Email" %}:</td>
          <td>{{ object.email }}</td>
        </tr>
        <tr>
          <td>{% trans "Is Active?" %}:</td>
          <td>
            {% if user.is_active %}
              <i class="material-icons">check_circle</i>
            {% else %}
              <i class="material-icons">highlight_off</i>
            {% endif %}
          </td>
        </tr>
        <tr>
          <td>{% trans "is Staff?" %}:</td>
          <td>
            {% if user.is_staff %}
              <i class="material-icons">check_circle</i>
            {% else %}
              <i class="material-icons">highlight_off</i>
            {% endif %}
          </td>
        </tr>
        <tr>
          <td>{% trans "Is Superuser?" %}:</td>
          <td>
            {% if user.is_staff %}
              <i class="material-icons">check_circle</i>
            {% else %}
              <i class="material-icons">highlight_off</i>
            {% endif %}
          </td>
        </tr>
      </tbody>
    </table>

    {% if object == request.user %}
      <div class="col-sm-12">
        <a href="{% url 'users:list' %}" class="btn btn-raised btn-secondary pull-left">
          {% trans "Back" %}
        </a>
        <a class="btn btn-primary btn-raised pull-right" href="{% url 'users:update' %}" role="button">
          {% trans "Update Info" %}
        </a>
        <a class="btn btn-primary btn-raised pull-right" href="{% url 'account_email' %}" role="button">
          {% trans "Change E-Mail" %}
        </a>
      </div>
    {% else %}
      <div class="col-sm-12">
        <a href="{% url 'users:list' %}" class="btn btn-raised btn-secondary pull-left">
          {% trans "Back" %}
        </a>
      </div>
    {% endif %}
  </div>
{% endblock %}

opac_ssm/templates/users/user_form.html
{% extends "users/base.html" %}
{% load crispy_forms_tags static i18n %}

{% block title %}{{ user.username }}{% endblock %}
{% block page_header_title %}
  <a href="{% url 'users:list' %}">{% trans "Users" %}</a>:
{% endblock page_header_title %}

{% block inner %}
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">{{ user.username }}</h1>
    <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
      {% csrf_token %}
      {{ form|crispy }}
      <div class="control-group">
        <div class="controls">
          <a href="{% url 'users:list' %}" class="btn btn-raised btn-secondary">Back</a>
          <button type="submit" class="btn btn-raised btn-primary pull-right">Update</button>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

opac_ssm/templates/users/user_list.html
{% extends "users/base.html" %}
{% load static i18n %}
{% block title %}Users{% endblock title %}

{% block page_header_title %}
  <a href="{% url 'users:list' %}">{% trans "Users" %}</a>:
{% endblock page_header_title %}

{% block inner %}
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>{% trans "Username" %}</th>
          <th>{% trans "Email" %}</th>
          <th>{% trans "Is Active?" %}</th>
          <th>{% trans "is Staff?" %}</th>
          <th>{% trans "Is Superuser?" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for user in user_list %}
          <tr>
            <td>
              <a href="{% url 'users:detail' user.username %}">{{ user.username }}</a>
            </td>
            <td>
              {% if user.email %}{{ user.email }}{% else %}--{% endif %}
            </td>
            <td>
              {% if user.is_active %}
                <i class="material-icons">check_circle</i>
              {% else %}
                <i class="material-icons">highlight_off</i>
              {% endif %}
            </td>
            <td>
              {% if user.is_staff %}
                <i class="material-icons">check_circle</i>
              {% else %}
                <i class="material-icons">highlight_off</i>
              {% endif %}
            </td>
            <td>
              {% if user.is_superuser %}
                <i class="material-icons">check_circle</i>
              {% else %}
                <i class="material-icons">highlight_off</i>
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock inner %}